apiVersion: v1
kind: Service
metadata:
    name: "myakscluster-fc8a"
    labels:
        app: "myakscluster-fc8a"
spec:
    type: LoadBalancer
    ports:
    - port: 8070
      targetPort: 8070
      protocol: TCP
      name: http
    selector:
        app: "myakscluster-fc8a"